/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/solutionssuite/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/solutionssuite/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/solutionssuite/AppSidebar.vue')['default']
    AppTabs: typeof import('./src/components/solutionssuite/AppTabs.vue')['default']
    AppWorkspace: typeof import('./src/components/solutionssuite/AppWorkspace.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/solutionssuite/Sidebar.vue')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Tree: typeof import('primevue/tree')['default']
  }
}
